# Generated by Django 5.2.8 on 2025-11-07 11:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss', models.CharField(max_length=20, unique=True, verbose_name='Social Security Number')),
                ('nom', models.CharField(max_length=50, verbose_name='Last Name')),
                ('prenom', models.CharField(max_length=50, verbose_name='First Name')),
                ('grade', models.CharField(max_length=100, verbose_name='Grade')),
                ('date_rec', models.DateField(verbose_name='Recruitment Date')),
                ('statut', models.CharField(choices=[('Actif', 'Active'), ('Congé', 'On Leave'), ('Retraité', 'Retired'), ('Démissionné', 'Resigned')], default='Actif', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Civil Servant',
                'verbose_name_plural': 'Civil Servants',
                'ordering': ['-date_rec'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_hired', models.DateField(default=datetime.date.today, verbose_name='Hire Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrative Staff',
                'verbose_name_plural': 'Administrative Staff',
                'ordering': ['-date_hired'],
            },
        ),
    ]
