# Generated by Django 5.2.8 on 2025-11-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prime', models.CharField(max_length=100, verbose_name='Bonus Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date_prime', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True)),
                ('fonctionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.fonctionnaire')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-date_prime'],
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20, verbose_name='Month')),
                ('annee', models.IntegerField(verbose_name='Year')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indemnites', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fonctionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.fonctionnaire')),
            ],
            options={
                'verbose_name': 'Salary Slip',
                'verbose_name_plural': 'Salary Slips',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('fonctionnaire', 'mois', 'annee')},
            },
        ),
    ]
