# Generated by Django 5.2.8 on 2025-11-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
            options={
                'verbose_name': 'Career History',
                'verbose_name_plural': 'Career Histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Echelon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echelon', models.DateField()),
                ('ancien_echelon', models.IntegerField(blank=True, null=True)),
                ('nouvel_echelon', models.IntegerField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('fonctionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.fonctionnaire')),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'ordering': ['-date_echelon'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_promotion', models.DateField()),
                ('ancien_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('nouveau_grade', models.CharField(max_length=100)),
                ('observation', models.TextField(blank=True, null=True)),
                ('fonctionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.fonctionnaire')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_promotion'],
            },
        ),
    ]
